# Generated by Django 2.1.1 on 2018-09-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('check-out', 'Check_out')], default='available', max_length=48),
        ),
    ]
